apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskhelloworld-deployment
  labels:
    app: flaskhelloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskhelloworld
  template:
    metadata:
      labels:
        app: flaskhelloworld
    spec:
      containers:
      - name: flaskhelloworld
        image: eu.gcr.io/vernal-tiger-346023/flaskhelloworld:0.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
