apiVersion: v1
kind: Service
metadata:
  name: flaskhelloworld-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: flaskhelloworld
  ports:
  - name: http
    port: 8181
    targetPort: 8181